spring:
  application:
    name: SpringSecEx

  datasource:
    url: jdbc:mysql://localhost:3306/ride_wawe?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#    user:
#      name: prabash
#      password: 12345
